package View;

import controller.GameBoardController;
import java.io.File;

/**
 *
 * @author gabardo
 */
public class GameSelectedLevelDefine extends javax.swing.JFrame {
    
    private GameBoardController gameController;

    /**
     * Creates new form GameCreateLevel
     */
    public GameSelectedLevelDefine(GameBoardController gameController) {
        this.gameController = gameController;
        initComponents();
    }
    
    public void selecionar(String nomeDaFase ){
        File file = new File("./src/main/resources/stages/"+ nomeDaFase +".txt");
        gameController.carregarPreSelecionado(file);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jbFase1 = new javax.swing.JButton();
        jbFase5 = new javax.swing.JButton();
        jbFase9 = new javax.swing.JButton();
        jbFase2 = new javax.swing.JButton();
        jbFase6 = new javax.swing.JButton();
        jbFase10 = new javax.swing.JButton();
        jbFase3 = new javax.swing.JButton();
        jbFase7 = new javax.swing.JButton();
        jbFase11 = new javax.swing.JButton();
        jbFase4 = new javax.swing.JButton();
        jbFase8 = new javax.swing.JButton();
        jbFase12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Campos da Fase");

        jbFase1.setText("Fase 1");
        jbFase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFase1ActionPerformed(evt);
            }
        });

        jbFase5.setText("Fase 5");
        jbFase5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFase5ActionPerformed(evt);
            }
        });

        jbFase9.setText("Fase 9");
        jbFase9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFase9ActionPerformed(evt);
            }
        });

        jbFase2.setText("Fase 2");
        jbFase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFase2ActionPerformed(evt);
            }
        });

        jbFase6.setText("Fase 6");
        jbFase6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFase6ActionPerformed(evt);
            }
        });

        jbFase10.setText("Fase 10");
        jbFase10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFase10ActionPerformed(evt);
            }
        });

        jbFase3.setText("Fase 3");
        jbFase3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFase3ActionPerformed(evt);
            }
        });

        jbFase7.setText("Fase 7");
        jbFase7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFase7ActionPerformed(evt);
            }
        });

        jbFase11.setText("Fase 11");
        jbFase11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFase11ActionPerformed(evt);
            }
        });

        jbFase4.setText("Fase 4");
        jbFase4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFase4ActionPerformed(evt);
            }
        });

        jbFase8.setText("Fase 8");
        jbFase8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFase8ActionPerformed(evt);
            }
        });

        jbFase12.setText("Fase 12");
        jbFase12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFase12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbFase2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbFase6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbFase10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbFase1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbFase5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbFase9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbFase3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbFase7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbFase11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbFase4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbFase8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbFase12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbFase1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFase5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFase9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbFase2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFase6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFase10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbFase3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFase7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFase11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbFase4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFase8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFase12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbFase12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFase12ActionPerformed
        this.selecionar("nivel12.0");
    }//GEN-LAST:event_jbFase12ActionPerformed

    private void jbFase8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFase8ActionPerformed
        this.selecionar("nivel8.0");
    }//GEN-LAST:event_jbFase8ActionPerformed

    private void jbFase4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFase4ActionPerformed
        this.selecionar("nivel4.0");
    }//GEN-LAST:event_jbFase4ActionPerformed

    private void jbFase11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFase11ActionPerformed
        this.selecionar("nivel11.0");
    }//GEN-LAST:event_jbFase11ActionPerformed

    private void jbFase7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFase7ActionPerformed
        this.selecionar("nivel7.0");
    }//GEN-LAST:event_jbFase7ActionPerformed

    private void jbFase3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFase3ActionPerformed
        this.selecionar("nivel3.0");
    }//GEN-LAST:event_jbFase3ActionPerformed

    private void jbFase10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFase10ActionPerformed
        this.selecionar("nivel10.0");
    }//GEN-LAST:event_jbFase10ActionPerformed

    private void jbFase6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFase6ActionPerformed
        this.selecionar("nivel6.0");
    }//GEN-LAST:event_jbFase6ActionPerformed

    private void jbFase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFase2ActionPerformed
        this.selecionar("nivel2.0");
    }//GEN-LAST:event_jbFase2ActionPerformed

    private void jbFase9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFase9ActionPerformed
        this.selecionar("nivel9.0");
    }//GEN-LAST:event_jbFase9ActionPerformed

    private void jbFase5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFase5ActionPerformed
        this.selecionar("nivel5.0");
    }//GEN-LAST:event_jbFase5ActionPerformed

    private void jbFase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFase1ActionPerformed
        this.selecionar("nivel1.0");
    }//GEN-LAST:event_jbFase1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbFase1;
    private javax.swing.JButton jbFase10;
    private javax.swing.JButton jbFase11;
    private javax.swing.JButton jbFase12;
    private javax.swing.JButton jbFase2;
    private javax.swing.JButton jbFase3;
    private javax.swing.JButton jbFase4;
    private javax.swing.JButton jbFase5;
    private javax.swing.JButton jbFase6;
    private javax.swing.JButton jbFase7;
    private javax.swing.JButton jbFase8;
    private javax.swing.JButton jbFase9;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
